server:
    port: 8188
    context-path:
    session:
      timeout: 60000
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.251:3306/zfqf?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ntnt2016
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    thymeleaf:
      cache: false
    mvc:
      view:
        forwardHttp10Compatible: false
      servlet:
        load-on-startup: 1
security:
  basic:
    enabled: false
  user:
    password: password
logging:
  level:
     com.payinxl: DEBUG
     org:
       springframework:
                  security: INFO
                  boot:
                    actuate:
                       audit:
                         listener:
                            AuditListener: DEBUG
  file: /app/cpdrserver/log/payinxl.log
mybatis:
  type-aliases-package: com.payinxl.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
website:
   email: 785343781@qq.com
   telphone: 13901673568
   qq: 785343781
   qq2: 3497917385
   sitename: 操盘牛人
   copyright: Copyright © 2017 - 2018 suodui.cn Corporation, All Rights Reserved